export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      hospitals: {
        Row: {
          hospital_id: string;
          name: string;
          type: string;
          address: string | null;
          city: string | null;
          state: string | null;
          pincode: string | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          abdm_facility_id: string | null;
          logo_url: string | null;
          is_active: boolean;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          hospital_id?: string;
          name: string;
          type: string;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          pincode?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          abdm_facility_id?: string | null;
          logo_url?: string | null;
          is_active?: boolean;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["hospitals"]["Insert"]>;
        Relationships: [];
      };
      doctors: {
        Row: {
          doctor_id: string;
          hospital_id: string | null;
          department_id: string | null;
          full_name: string;
          email: string;
          phone: string | null;
          gender: string | null;
          specialization: string;
          designation: string | null;
          mci_registration_no: string | null;
          years_of_experience: number | null;
          languages_spoken: string[];
          profile_image_url: string | null;
          certificate_url: string | null;
          id_document_url: string | null;
          digital_signature: string | null;
          is_onboarded: boolean;
          is_active: boolean;
          last_login_at: string | null;
          preferred_language: string;
          soap_template: Json | null;
          notification_prefs: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          doctor_id?: string;
          hospital_id?: string | null;
          department_id?: string | null;
          full_name: string;
          email: string;
          phone?: string | null;
          gender?: string | null;
          specialization: string;
          designation?: string | null;
          mci_registration_no?: string | null;
          years_of_experience?: number | null;
          languages_spoken?: string[];
          profile_image_url?: string | null;
          certificate_url?: string | null;
          id_document_url?: string | null;
          digital_signature?: string | null;
          is_onboarded?: boolean;
          is_active?: boolean;
          last_login_at?: string | null;
          preferred_language?: string;
          soap_template?: Json | null;
          notification_prefs?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["doctors"]["Insert"]>;
        Relationships: [];
      };
      patients: {
        Row: {
          patient_id: string;
          hospital_id: string | null;
          full_name: string;
          email: string | null;
          phone: string | null;
          gender: string | null;
          date_of_birth: string | null;
          age: number | null;
          blood_group: string | null;
          abha_id: string | null;
          abha_address: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          pincode: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          emergency_contact_rel: string | null;
          known_allergies: Json;
          chronic_conditions: Json;
          current_medications: Json;
          vaccination_history: Json;
          family_history: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          patient_id?: string;
          hospital_id?: string | null;
          full_name: string;
          email?: string | null;
          phone?: string | null;
          gender?: string | null;
          date_of_birth?: string | null;
          age?: number | null;
          blood_group?: string | null;
          abha_id?: string | null;
          abha_address?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          pincode?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          emergency_contact_rel?: string | null;
          known_allergies?: Json;
          chronic_conditions?: Json;
          current_medications?: Json;
          vaccination_history?: Json;
          family_history?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["patients"]["Insert"]>;
        Relationships: [];
      };
      consultations: {
        Row: {
          consultation_id: string;
          doctor_id: string;
          patient_id: string;
          hospital_id: string;
          status: string;
          consultation_type: string;
          chief_complaint: string | null;
          scheduled_at: string | null;
          started_at: string | null;
          ended_at: string | null;
          duration_seconds: number | null;
          language_detected: string | null;
          audio_url: string | null;
          audio_storage_path: string | null;
          audio_duration_sec: number | null;
          transcript_raw: string | null;
          transcript_cleaned: string | null;
          speaker_segments: Json | null;
          abdm_synced: boolean;
          abdm_synced_at: string | null;
          abdm_record_id: string | null;
          notes: string | null;
          room_number: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          consultation_id?: string;
          doctor_id: string;
          patient_id: string;
          hospital_id: string;
          status?: string;
          consultation_type?: string;
          chief_complaint?: string | null;
          scheduled_at?: string | null;
          started_at?: string | null;
          ended_at?: string | null;
          duration_seconds?: number | null;
          language_detected?: string | null;
          audio_url?: string | null;
          audio_storage_path?: string | null;
          audio_duration_sec?: number | null;
          transcript_raw?: string | null;
          transcript_cleaned?: string | null;
          speaker_segments?: Json | null;
          abdm_synced?: boolean;
          abdm_synced_at?: string | null;
          abdm_record_id?: string | null;
          notes?: string | null;
          room_number?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["consultations"]["Insert"]>;
        Relationships: [];
      };
      soap_notes: {
        Row: {
          note_id: string;
          consultation_id: string;
          doctor_id: string;
          patient_id: string;
          subjective: string | null;
          objective: string | null;
          assessment: string | null;
          plan: string | null;
          extracted_symptoms: Json;
          extracted_vitals: Json;
          extracted_diagnoses: Json;
          extracted_medications: Json;
          extracted_procedures: Json;
          icd10_codes: Json;
          ai_confidence_score: number | null;
          ai_model_version: string | null;
          generation_time_ms: number | null;
          doctor_feedback: string | null;
          is_approved: boolean;
          approved_at: string | null;
          version: number;
          parent_note_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          note_id?: string;
          consultation_id: string;
          doctor_id: string;
          patient_id: string;
          subjective?: string | null;
          objective?: string | null;
          assessment?: string | null;
          plan?: string | null;
          extracted_symptoms?: Json;
          extracted_vitals?: Json;
          extracted_diagnoses?: Json;
          extracted_medications?: Json;
          extracted_procedures?: Json;
          icd10_codes?: Json;
          ai_confidence_score?: number | null;
          ai_model_version?: string | null;
          generation_time_ms?: number | null;
          doctor_feedback?: string | null;
          is_approved?: boolean;
          approved_at?: string | null;
          version?: number;
          parent_note_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["soap_notes"]["Insert"]>;
        Relationships: [];
      };
      reports: {
        Row: {
          report_id: string;
          patient_id: string;
          consultation_id: string | null;
          uploaded_by: string;
          report_type: string;
          title: string;
          file_url: string;
          storage_path: string;
          mime_type: string | null;
          file_size_bytes: number | null;
          ai_extracted_values: Json;
          abnormal_flags: Json;
          ai_summary: string | null;
          ai_model_version: string | null;
          report_date: string | null;
          lab_name: string | null;
          referring_doctor: string | null;
          notes: string | null;
          is_archived: boolean;
          created_at: string;
        };
        Insert: {
          report_id?: string;
          patient_id: string;
          consultation_id?: string | null;
          uploaded_by: string;
          report_type: string;
          title: string;
          file_url: string;
          storage_path: string;
          mime_type?: string | null;
          file_size_bytes?: number | null;
          ai_extracted_values?: Json;
          abnormal_flags?: Json;
          ai_summary?: string | null;
          ai_model_version?: string | null;
          report_date?: string | null;
          lab_name?: string | null;
          referring_doctor?: string | null;
          notes?: string | null;
          is_archived?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["reports"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
